// user
export const CHANGE_LOGIN_STATUS  = 'CHANGE_LOGIN_STATUS';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_ID = 'SET_USER_ID';
export const CHANGE_NAME_INPUT = 'CHANGE_NAME_INPUT';
export const CHANGE_NAME = 'CHANGE_NAME';

// list
export const SET_SENTENCE_LIST = 'SET_SENTENCE_LIST';
export const SHOW_MORE_SENTENCE_BODY = 'SHOW_MORE_SENTENCE_BODY';
export const CLEAR_LIST_ITEM = 'CLEAR_LIST_ITEM';
export const CHAHNGE_LIST_ITEM = 'CHAHNGE_LIST_ITEM';