// common
export const TOGGLE_POPUP = 'TOGGLE_POPUP';

// user
export const CHANGE_LOGIN_STATUS  = 'CHANGE_LOGIN_STATUS';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_ID = 'SET_USER_ID';
export const CHANGE_NAME_INPUT = 'CHANGE_NAME_INPUT';
export const CHANGE_NAME = 'CHANGE_NAME';

// list
export const SET_SENTENCE_LIST = 'SET_SENTENCE_LIST';
export const SHOW_MORE_SENTENCE_BODY = 'SHOW_MORE_SENTENCE_BODY';
export const CLEAR_LIST_ITEM = 'CLEAR_LIST_ITEM';
export const CHAHNGE_LIST_ITEM = 'CHAHNGE_LIST_ITEM';

// book
export const RESET_BOOK_STATE = 'RESET_BOOK_STATE';
export const SHOW_INPUT_ALERT = 'SHOW_INPUT_ALERT';
export const INPUT_BOOK_SEARCH = 'INPUT_BOOK_SEARCH';
export const SET_BOOK_SEARCH_RESULT = 'SET_BOOK_SEARCH_RESULT';
export const SELECT_SEARCHED_BOOK = 'SELECT_SEARCHED_BOOK';
export const SHOW_BOOKINFO_INPUT = 'SHOW_BOOKINFO_INPUT';
export const CHANGE_BOOKINFO_INPUT = 'CHANGE_BOOKINFO_INPUT';
export const SUBMIT_BOOKINFO_INPUT = 'SUBMIT_BOOKINFO_INPUT';
export const CHANGE_SENTENCE_TEXTAREA = 'CHANGE_SENTENCE_TEXTAREA';
export const SUBMIT_SENTENCE = 'SUBMIT_SENTENCE';